[package]
name = "pseugo"
version = "0.1.0"
description = "Create algorithm pseudo code easily"
authors = ["Daniel da Silva <daniel@doetdingen.nl>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
